// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded values for now to fix the environment variable issue
const SUPABASE_URL = "https://mkuojjqhpfsnxhtizmri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdW9qanFocGZzbnhodGl6bXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxNTA4OTQsImV4cCI6MjA3NTcyNjg5NH0.NRrztDE4Zc7d2GPXJVGs3GWpBhmZRnzJr800lhd8NSU";

// Debug: Log the values
console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase Key:', SUPABASE_PUBLISHABLE_KEY ? 'Present' : 'Missing');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);